name: Publish Python Package

on:
  workflow_run:
    workflows: ["Tag After Bump"]
    types:
      - completed
  workflow_dispatch:

jobs:
  publish:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install -U build twine setuptools wheel

      - name: Install dependencies
        run: |
          python -m pip install --upgrade build twine

      - name: Compile translations
        run: |
          pip install babel
          pybabel compile -d src/novel_downloader/locales

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
